# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SunnuntaiTesti',
                'doc_host': 'https://Harri1970.github.io',
                'git_url': 'https://github.com/Harri1970/SunnuntaiTesti',
                'lib_path': 'SunnuntaiTesti'},
  'syms': {'SunnuntaiTesti.core': {'SunnuntaiTesti.core.foo': ('core.html#foo', 'SunnuntaiTesti/core.py')}}}
